export const GET = "GET";
export const POST = "POST";
export const PATCH = "PATCH";
export const DELETE = "DELETE";
export const ADMIN = "ADMIN";
export const USER = "USER";

export const TOKEN_SUCCESS = "TOKEN_SUCCESS";
export const TOKEN_FAIL = "TOKEN_FAIL";

export const FETCH_USER = "FETCH_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const FETCH_DOMAINS = "FETCH_DOMAINS";
export const SAVING_DOMAIN = "SAVING_DOMAIN";
export const DOMAINS_SUCCESS = "DOMAINS_SUCCESS";
export const DOMAINS_FAIL = "DOMAINS_FAIL";
export const DELETING_DOMAIN = "DELETING_DOMAIN";

export const SAVING_EVENT = "SAVING_EVENT";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const EVENTS_SUCCESS = "EVENTS_SUCCESS";
export const EVENT_SUCCESS = "EVENT_SUCCESS";
export const EVENTS_FAIL = "EVENTS_FAIL";
export const EVENT_FAIL = "EVENTS_FAIL";
export const DELETING_EVENT = "DELETING_EVENT";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";

export const SAVING_KEYWORDS = "SAVING_KEYWORDS";
export const KEYWORDS_SUCCESS = "KEYWORDS_SUCCESS";
export const KEYWORDS_FAIL = "KEYWORDS_FAIL";
export const DELETING_KEYWORDS = "DELETING_KEYWORDS";

export const SYNC_REPORT = "SYNC_REPORT";
export const GENERATE_REPORT = "GENERATE_REPORT";
export const FETCH_REPORT = "FETCH_REPORT";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAIL = "REPORT_FAIL";
export const DELETING_REPORT = "DELETING_REPORT";
export const GENERATE_REPORT_BY_KEYWORD = "GENERATE_REPORT_BY_KEYWORD";

export const FILTERING = "FILTERING";
export const FILTER_REPORT = "FILTER_REPORT";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const COUNT_SUCCESS = "COUNT_SUCCESS";
export const COUNT_FAIL = "COUNT_FAIL";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAIL = "LANGUAGES_FAIL";

export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const LOCATIONS_SUCCESS = "LOCATIONS_SUCCESS";
export const LOCATIONS_FAIL = "LOCATIONS_FAIL";

export const FETCH_USERS = "FETCH_USERS";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAIL = "USERS_FAIL";

export const CREATING_USER = "CREATING_USER";
export const CREATE_USER = "CREATE_USER";
export const USER_FAIL = "USER_FAIL";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const GET_USERS_DOMAIN_SUCCESS = "GET_USERS_DOMAIN_SUCCESS";
export const GET_USERS_DOMAIN_FAIL = "GET_USERS_DOMAIN_FAIL";

export const FETCH_USER_DOMAINS = "FETCH_USER_DOMAINS";
export const GET_USER_DOMAINS_BY_ID_SUCCESS = "GET_USER_DOMAINS_BY_ID_SUCCESS";
export const GET_USER_DOMAINS_BY_ID_FAIL = "GET_USER_DOMAINS_BY_ID_FAIL";
export const CLEAR_USER_DOMAINS_BY_ID = "CLEAR_USER_DOMAINS_BY_ID";

export const USER_DOMAINS_ACCESS_SUCCESS = "USER_DOMAINS_ACCESS_SUCCESS";
export const USER_DOMAINS_ACCESS_FAIL = "USER_DOMAINS_ACCESS_FAIL";

export const SHOW_NOTIFICATION_SUCCESS = "SHOW_NOTIFICATION_SUCCESS"
export const SHOW_NOTIFICATION_FAIL = "SHOW_NOTIFICATION_FAIL"


// Visited User Constant
export const SAVING_VISITEDUSER = "SAVING_VISITEDUSER";
export const FETCH_VISITEDUSER = "FETCH_VISITEDUSER";
export const VISITEDUSER_SUCCESS = "VISITEDUSER_SUCCESS";
export const VISITEDUSERS_SUCCESS = "VISITEDUSERS_SUCCESS";
export const VISITEDUSER_FAIL = "VISITEDUSER_FAIL";
export const VISITEDUSERS_FAIL = "VISITEDUSERS_FAIL";
export const DELETING_VISITEDUSER = "DELETING_VISITEDUSER";

export const CREATE_VISITEDUSER_SUCCESS = "CREATE_VISITEDUSER_SUCCESS";
export const CREATE_VISITEDUSER_FAIL = "CREATE_VISITEDUSER_FAIL";

export const VISITEDUSER_NAME = "VISITEDUSER_NAME";
export const VISITEDUSER_EMAIL = "VISITEDUSER_EMAIL";
export const VISITEDUSER_PHONENO = "VISITEDUSER_PHONENO";
export const VISITEDUSER_EVENTID = "VISITEDUSER_EVENTID";

export const EDIT_VISITEDUSER_ID = "EDIT_VISITEDUSER_ID";
export const EDIT_VISITEDUSER_NAME = "EDIT_VISITEDUSER_NAME";
export const EDIT_VISITEDUSER_EMAIL = "EDIT_VISITEDUSER_EMAIL";
export const EDIT_VISITEDUSER_PHONENO = "EDIT_VISITEDUSER_PHONENO";
export const EDIT_VISITEDUSER_EVENTID = "EDIT_VISITEDUSER_EVENTID";

export const EDIT_VISITEDUSER_SUCCESS = "EDIT_VISITEDUSER_SUCCESS";
export const EDIT_VISITEDUSER_FAIL = "EDIT_VISITEDUSER_FAIL";

// dashboard
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";
export const CHANGE_DASHBOARD_STATE = "CHANGE_DASHBOARD_STATE";